name: Publish Docker Image

# 当代码推送到 `main` 分支时触发工作流
on:
  push:
    branches:
      - main

# 工作流中的任务
jobs:
  build-and-push:
    # 在最新的 Ubuntu 系统上运行
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 设置QEMU以支持多平台构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # 设置Buildx以支持多平台构建
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录到 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 构建并推送 Docker 镜像
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/src:latest
          file: ./Dockerfile
      
      # 推送 README.md 到 Docker Hub
      - name: Push README to Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/src
